services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres -U postgres --command 'SELECT 1'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    networks:
#      - pact-network

  broker:
    image: pactfoundation/pact-broker:latest-multi
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 9292:9292
    restart: always
    environment:
      # Basic auth credentials for the Broker
      PACT_BROKER_ALLOW_PUBLIC_READ: 'true'
      PACT_BROKER_BASIC_AUTH_USERNAME: pactbroker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pactbroker
      PACT_BROKER_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    healthcheck:
      test:
        - CMD
        - wget
        - -q
        - -O
        - '-'
        - http://pactbroker:pactbroker@broker:9292/diagnostic/status/heartbeat
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 10s
#    networks:
#      - pact-network

#networks:
#  pact-network:
#    driver: bridge